CREATE TABLE [dbo].[Employee]
(
	[Id] INT NOT NULL PRIMARY KEY CLUSTERED IDENTITY(1, 1),
	[Guid] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	[FirstName] VARCHAR(100) NOT NULL,
	[LastName] VARCHAR(100) NOT NULL,
	[DateOfBirth] DATETIME NOT NULL,
	[EncryptedSSN] VARCHAR(MAX) NOT NULL,
	[CreatedAtDateTimeUTC] DATETIME NOT NULL DEFAULT GETUTCDATE()
)
